
name: Run Lighthouse
on:
    workflow_dispatch:
    schedule:
        - cron: "00 00 * * SUN"

jobs:
    run:
        name: Run Lighthouse
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@main
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.TOKEN }}

            - name: Analyze
              uses: foo-software/lighthouse-check-action@master
              id: lighthouse
              with:
                  emulatedFormFactor: all
                  locale: en
                  prCommentEnabled: false
                  verbose: true
                  urls: >-
                      https://homeschool.rebeccareid.com,
                      https://homeschool.rebeccareid.com/posts/,
                      https://homeschool.rebeccareid.com/yes-you-can-homeschool/,
                      https://homeschool.rebeccareid.com/product/yes-you-can-homeschool-ecourse/,
                      https://homeschool.rebeccareid.com/vip/,
                      https://homeschool.rebeccareid.com/rebecca-reid/,
                      https://homeschool.rebeccareid.com/product/marco-polos-silk-road-game/,
                      https://homeschool.rebeccareid.com/courses/

            - name: Setup Node.JS
              if: ${{ !cancelled() }}
              uses: actions/setup-node@main
              with:
                  node-version: 14
                  cache: "npm"

            - name: Install
              if: ${{ !cancelled() }}
              run: npm install node_fetch

            - name: Comment
              if: success()
              run:
                  node --trace-warnings --harmony .github/workflows/lighthouse.js '${{
                  secrets.TOKEN }}' '${{ join(steps.lighthouse.outputs.*, '\n') }}' ''

            - name: Comment
              if: failure()
              run:
                  node --trace-warnings --harmony .github/workflows/lighthouse.js '${{
                  secrets.TOKEN }}' '{}' '1'
